window.FooddeeData = {
  products: [
    {
      id: "burger",
      name: "Cheese Burger",
      category: "Burgers",
      price: 149,
      rating: 4.6,
      reviews: 128,
      image: "assets/food/dishes/cheese-burger.png",
      desc: "Juicy grilled patty with cheese, fresh lettuce, tomato, onion and our special sauce in a soft sesame bun.",
    },
    {
      id: "pizza",
      name: "Veggie Pizza",
      category: "Pizza",
      price: 249,
      rating: 4.5,
      reviews: 96,
      image: "assets/food/dishes/veggie-pizza.png",
      desc: "Loaded with fresh veggies, mozzarella cheese and a bright tomato sauce.",
    },
    {
      id: "pasta",
      name: "Creamy Alfredo Pasta",
      category: "Pasta",
      price: 199,
      rating: 4.7,
      reviews: 112,
      image: "assets/food/dishes/alfredo-pasta.png",
      desc: "Rich white sauce pasta finished with herbs and creamy cheese.",
    },
    {
      id: "fries",
      name: "French Fries",
      category: "Snacks",
      price: 99,
      rating: 4.3,
      reviews: 84,
      image: "assets/food/dishes/french-fries.png",
      desc: "Crispy golden fries with a pinch of salt.",
    },
    {
      id: "chicken",
      name: "Fried Chicken",
      category: "Chicken",
      price: 199,
      rating: 4.6,
      reviews: 104,
      image: "assets/food/dishes/crispy-chicken.png",
      desc: "Crispy juicy chicken with warm spices and a golden crust.",
    },
    {
      id: "drink",
      name: "Lime Mint Cooler",
      category: "Drinks",
      price: 89,
      rating: 4.4,
      reviews: 77,
      image: "assets/food/dishes/lime-mint-cooler.png",
      desc: "Refreshing lime drink with mint and ice.",
    },
    {
      id: "salad",
      name: "Fresh Garden Salad",
      category: "Salads",
      price: 149,
      rating: 4.5,
      reviews: 92,
      image: "assets/food/dishes/garden-salad.png",
      desc: "Fresh greens, cucumber, tomato and soft cheese tossed lightly.",
    },
    {
      id: "cake",
      name: "Chocolate Cake",
      category: "Desserts",
      price: 129,
      rating: 4.8,
      reviews: 135,
      image: "assets/food/dishes/chocolate-cake.png",
      desc: "Moist chocolate cake with rich ganache.",
    },
  ],

  categories: [
    { name: "Burgers", icon: "assets/food/categories/burgers.png" },
    { name: "Pizza", icon: "assets/food/categories/pizzas.png" },
    { name: "Pasta", icon: "assets/food/categories/pasta.png" },
    { name: "Chicken", icon: "assets/food/categories/chicken.png" },
    { name: "Salads", icon: "assets/food/categories/salads.png" },
    { name: "Drinks", icon: "assets/food/categories/drinks.png" },
    { name: "Desserts", icon: "assets/food/categories/desserts.png" },
  ],

  initialCart: [
    { id: "burger", qty: 1 },
    { id: "fries", qty: 1 },
    { id: "drink", qty: 1 },
  ],
};
